### ISSUE TITLE
Issue in installation 

### ISSUE THREAD

**Issue by Anujmoglix** [Anyline/react-native-image-to-pdf#8]
Hi ,
  After installation i am getting 

> Dex: Error converting bytecode to dex:
> Cause: com.android.dex.DexIndexOverflowException: Cannot merge new index 66550 into a non-jumbo instruction!
>     UNEXPECTED TOP-LEVEL EXCEPTION:
>     com.android.dex.DexIndexOverflowException: Cannot merge new index 66550 into a non-jumbo instruction!
>         at com.android.dx.merge.InstructionTransformer.jumboCheck(InstructionTransformer.java:132)
>         at com.android.dx.merge.InstructionTransformer.access$1000(InstructionTransformer.java:26)
>         at com.android.dx.merge.InstructionTransformer$StringVisitor.visit(InstructionTransformer.java:76)
>         at com.android.dx.io.CodeReader.callVisit(CodeReader.java:130)
>         at com.android.dx.io.CodeReader.visitAll(CodeReader.java:103)
>         at com.android.dx.merge.InstructionTransformer.transform(InstructionTransformer.java:52)
>         at com.android.dx.merge.DexMerger.transformCode(DexMerger.java:907)
>         at com.android.dx.merge.DexMerger.transformMethods(DexMerger.java:881)
>         at com.android.dx.merge.DexMerger.transformClassData(DexMerger.java:853)
>         at com.android.dx.merge.DexMerger.transformClassDef(DexMerger.java:750)
>         at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:604)
>         at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
>         at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
>         at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:506)
>         at com.android.dx.command.dexer.Main.runMonoDex(Main.java:336)
>         at com.android.dx.command.dexer.Main.runDx(Main.java:291)
>         at com.android.dx.command.dexer.Main.main(Main.java:247)
>         at com.android.dx.command.Main.main(Main.java:94)
>     
> :app:transformClassesWithDexForDebug FAILED
> 
> FAILURE: Build failed with an exception.
>

**Comment by ale-anyline** [comment]
Hi,
Have you already tried the change suggested in this [post](https://stackoverflow.com/questions/26093664/dexexception-cannot-merge-new-index-65536-into-a-non-jumbo-instruction)? Thanks
